### ISSUE TITLE
Combine and simplify item decorators.

### ISSUE THREAD

**Issue by BurnzZ** [zytedata/zyte-common-items#5]
Currently, items are declared like:

```python
import attrs
from zyte_common_items.util import export

@export
@attrs.define(slots=True, kw_only=True)
class SomeItem:
    ...
```

It would be nice if we can combine the two decorators into a single one to have a more concise code.

**Comment by Gallaecio** [comment]
> [We can also drop the `export` decorator :)](https://github.com/zytedata/zyte-common-items/pull/2#discussion_r904754106)
